apply plugin: 'org.jetbrains.kotlin.kapt'

dependencies {
    api project(":artifact")
    api project(":artifact-services")
    api project(":artifact-services-dotnet")
    api project(":dsl-services-dotnet")
    implementation project(":dsl-services-dotnet-asp")
    implementation project(":resolve")
    implementation project(":resolve-services-dotnet-asp")
    api libs.spi.tooling.annotations
    kapt libs.spi.tooling.processor
}
