kotlin.code.style=official
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.warning.mode=all
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx2g
