import org.gradle.caching.http.HttpBuildCache

pluginManagement {
    includeBuild('build-logic')
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
        id 'org.jetbrains.kotlin.jvm' version '2.2.21'
        id 'org.jetbrains.kotlin.kapt' version '2.2.21'
        id 'pl.allegro.tech.build.axion-release' version '1.21.0'
        id 'io.kotest' version '6.0.1'
        id 'io.gitlab.arturbosch.detekt' version '1.23.8'
        id 'org.jlleitschuh.gradle.ktlint' version '12.1.2'
        id 'com.gradleup.shadow' version '9.2.2'
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention'
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        mavenCentral()
        maven {
            url = uri("https://repo.scala-sbt.org/scalasbt/maven-releases/")
        }
        maven {
            url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
            mavenContent {
                snapshotsOnly()
            }
        }
    }
}

buildCache {
    local {
        enabled = true
    }
    def remoteCacheUrl = providers.environmentVariable("GRADLE_HTTP_CACHE_URL").orNull
    if (remoteCacheUrl) {
        remote(HttpBuildCache) {
            url = uri(remoteCacheUrl)
            push = providers.environmentVariable("CI").isPresent()
            credentials {
                username = providers.environmentVariable("GRADLE_HTTP_CACHE_USERNAME").orNull
                password = providers.environmentVariable("GRADLE_HTTP_CACHE_PASSWORD").orNull
            }
            allowInsecureProtocol = false
        }
    }
}

rootProject.name = 'microsmith'

[
    'dsl',
    'dsl-services',
    'dsl-services-dotnet',
    'dsl-services-dotnet-asp',
    'dsl-services-dotnet-packages',
    'dsl-schemas',
    'dsl-schemas-protobuf',
    'dsl-schemas-protobuf-rpc',
    'resolve',
    'resolve-services',
    'resolve-services-dotnet',
    'resolve-services-dotnet-asp',
    'resolve-services-dotnet-packages',
    'resolve-schemas',
    'resolve-schemas-protobuf',
    'resolve-schemas-protobuf-rpc',
    'artifact',
    'artifact-schemas',
    'artifact-schemas-protobuf',
    'artifact-schemas-protobuf-rpc',
    'artifact-services',
    'artifact-services-dotnet',
    'artifact-services-dotnet-asp',
    'artifact-services-dotnet-packages',
    'compile',
    'compile-schemas',
    'compile-schemas-protobuf',
    'compile-schemas-protobuf-rpc',
    'compile-services',
    'compile-services-dotnet',
    'compile-services-dotnet-asp',
    'compile-services-dotnet-packages',
    'gen',
    'runtime-scripting',
    'cli',
    'gradle-plugin',
    'maven-plugin',
    'sbt-plugin',
    'kotest',
].each { moduleName ->
    include moduleName
    project(":${moduleName}").projectDir = file("modules/${moduleName}")
}
