package io.github.lmliam.microsmith.cli.ide

import java.nio.file.Path

internal object IdeHelperProjectTemplates {
    fun renderSettingsGradle(): String = """
        rootProject.name = "microsmith-ide-helper"
    """.trimIndent() + "\n"

    fun renderBuildGradle(classpathEntries: List<Path>): String {
        val dependencyEntries =
            classpathEntries.joinToString(separator = ",\n") { entry ->
                "            \"${entry.toKotlinPathLiteral()}\""
            }

        return buildString {
            appendLine("plugins {")
            appendLine("    id(\"java-library\")")
            appendLine("}")
            appendLine()
            appendLine("dependencies {")
            appendLine("    implementation(")
            appendLine("        files(")
            appendLine(dependencyEntries)
            appendLine("        )")
            appendLine("    )")
            appendLine("}")
        }
    }

    fun renderReadme(): String = """
        # Microsmith JetBrains IDE Helper

        This directory is generated by `microsmith ide refresh`.

        Purpose:
        - provide a minimal Gradle model that exposes Microsmith script-definition/runtime types
        - improve `.microsmith.kts` indexing and type resolution in JetBrains IDEs

        Default first-run path:
        - run `microsmith init` from the repository root unless helper generation was skipped intentionally

        Lifecycle commands:
        - run `microsmith ide refresh` to generate or resynchronize the helper
        - run `microsmith ide doctor --diagnostics json --verbose` when the helper appears stale or symbols remain unresolved

        Usage:
        1. run `microsmith init`, or `microsmith ide refresh` if helper generation was skipped earlier
        2. in your JetBrains IDE, link/import `.microsmith/ide/build.gradle.kts` as a Gradle project
        3. refresh Gradle after upgrading Microsmith CLI or plugin dependencies

        Repository hygiene:
        - treat `.microsmith/ide/` as local generated IDE state
        - add `.microsmith/ide/` to your repository `.gitignore`
        - Microsmith manages only `settings.gradle.kts`, `build.gradle.kts`, and `README.md` in this directory
        - do not hand-edit those managed files; rerun `microsmith ide refresh` instead

        Regeneration:
        - command is idempotent and safe to rerun
        - only files inside `.microsmith/ide` are managed
    """.trimIndent() + "\n"
}
