package io.github.lmliam.microsmith.cli.parsing

internal const val INIT_COMMAND = "init"
internal const val RUN_COMMAND = "run"
internal const val DOCTOR_COMMAND = "doctor"
internal const val IDE_COMMAND = "ide"
internal const val IDE_REFRESH_SUBCOMMAND = "refresh"
internal const val IDE_DOCTOR_SUBCOMMAND = "doctor"
internal const val OUTPUT_OPTION = "--out"
internal const val VARIABLE_OPTION = "--var"
internal const val FLAG_OPTION = "--flag"
internal const val PLUGIN_OPTION = "--plugin"
internal const val PLUGIN_JAR_OPTION = "--plugin-jar"
internal const val OFFLINE_OPTION = "--offline"
internal const val REPOSITORY_OPTION = "--repository"
internal const val ISOLATION_OPTION = "--isolation"
internal const val DIAGNOSTICS_OPTION = "--diagnostics"
internal const val VERBOSE_OPTION = "--verbose"
internal const val EVENT_LOG_OPTION = "--event-log"
internal const val REPO_ROOT_OPTION = "--repo-root"
internal const val FORCE_OPTION = "--force"
internal const val SKIP_IDE_HELPER_OPTION = "--skip-ide-helper"
internal const val SCRIPT_EXTENSION = ".microsmith.kts"
internal val HELP_COMMANDS = setOf("--help", "-h", "help")
internal val VERSION_COMMANDS = setOf("--version")
