package me.liam.microsmith.cli.ide

import me.liam.microsmith.cli.command.IdeRefreshCommand
import java.io.File
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.LinkOption
import java.nio.file.Path

internal fun refreshIdeHelperProject(
    command: IdeRefreshCommand,
    classpathResolver: () -> List<Path> = ::resolveIdeHelperClasspathEntries,
): IdeHelperRefreshResult {
    val projectRoot = command.projectRoot.toAbsolutePath().normalize()
    require(Files.exists(projectRoot)) {
        "Repository root '$projectRoot' does not exist."
    }
    require(Files.isDirectory(projectRoot)) {
        "Repository root '$projectRoot' is not a directory."
    }

    val helperRoot = projectRoot.resolve(IDE_HELPER_DIRECTORY).toAbsolutePath().normalize()
    val classpathEntries =
        classpathResolver()
            .map { path -> path.toAbsolutePath().normalize() }
            .filter(Files::exists)
            .distinctBy(Path::toString)
            .sortedBy(Path::toString)

    require(classpathEntries.isNotEmpty()) {
        "Could not resolve runtime classpath entries for IDE helper generation."
    }

    ensureManagedDirectory(projectRoot.resolve(".microsmith").toAbsolutePath().normalize())
    ensureManagedDirectory(helperRoot)

    val targetFiles =
        linkedMapOf(
            helperRoot.resolve(IDE_HELPER_SETTINGS_FILE_NAME) to renderSettingsGradle(),
            helperRoot.resolve(IDE_HELPER_BUILD_FILE_NAME) to renderBuildGradle(classpathEntries),
            helperRoot.resolve(IDE_HELPER_README_FILE_NAME) to renderReadme(),
        )

    val updatedFiles =
        buildList {
            targetFiles.forEach { (path, content) ->
                if (writeFileIfChanged(path, content)) {
                    add(path)
                }
            }
        }.sortedBy(Path::toString)

    return IdeHelperRefreshResult(
        projectRoot = projectRoot,
        helperRoot = helperRoot,
        updatedFiles = updatedFiles,
        classpathEntries = classpathEntries,
    )
}

internal fun resolveIdeHelperClasspathEntries(
    javaClasspath: String = System.getProperty("java.class.path").orEmpty(),
): List<Path> {
    if (javaClasspath.isBlank()) {
        return emptyList()
    }

    return javaClasspath
        .split(File.pathSeparator)
        .map(String::trim)
        .filter(String::isNotEmpty)
        .map(Path::of)
}

private fun renderSettingsGradle(): String = """
rootProject.name = "microsmith-ide-helper"
""".trimIndent() + "\n"

private fun renderBuildGradle(classpathEntries: List<Path>): String {
    val dependencyEntries =
        classpathEntries.joinToString(separator = ",\n") { entry ->
            "            \"${entry.toKotlinPathLiteral()}\""
        }

    return buildString {
        appendLine("plugins {")
        appendLine("    id(\"java-library\")")
        appendLine("}")
        appendLine()
        appendLine("dependencies {")
        appendLine("    implementation(")
        appendLine("        files(")
        appendLine(dependencyEntries)
        appendLine("        )")
        appendLine("    )")
        appendLine("}")
    }
}

private fun renderReadme(): String = """
# Microsmith JetBrains IDE Helper

This directory is generated by `microsmith ide refresh`.

Purpose:
- provide a minimal Gradle model that exposes Microsmith script-definition/runtime types
- improve `.microsmith.kts` indexing and type resolution in JetBrains IDEs

Usage:
1. run `microsmith ide refresh` from repository root
2. in your JetBrains IDE, link/import `.microsmith/ide/build.gradle.kts` as a Gradle project
3. refresh Gradle after upgrading Microsmith CLI or plugin dependencies

Regeneration:
- command is idempotent and safe to rerun
- only files inside `.microsmith/ide` are managed
""".trimIndent() + "\n"

private fun writeFileIfChanged(path: Path, content: String): Boolean {
    val normalizedContent = content.replace("\r\n", "\n")
    if (managedPathExists(path)) {
        if (!isManagedRegularFile(path)) {
            throw IdeHelperConflictException("IDE helper path '$path' exists but is not a regular file.")
        }
        val existing = Files.readString(path, StandardCharsets.UTF_8).replace("\r\n", "\n")
        if (existing == normalizedContent) {
            return false
        }
    }

    Files.writeString(path, normalizedContent, StandardCharsets.UTF_8)
    return true
}

private fun ensureManagedDirectory(path: Path) {
    when {
        managedPathExists(path) && isManagedDirectory(path) -> return
        managedPathExists(path) ->
            throw IdeHelperConflictException("IDE helper directory '$path' exists but is not a directory.")

        else -> Files.createDirectory(path)
    }
}

private fun managedPathExists(path: Path): Boolean = Files.exists(path, LinkOption.NOFOLLOW_LINKS)

private fun isManagedDirectory(path: Path): Boolean = Files.isDirectory(path, LinkOption.NOFOLLOW_LINKS)

private fun isManagedRegularFile(path: Path): Boolean = Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)

internal fun Path.toKotlinPathLiteral(): String = toAbsolutePath()
    .normalize()
    .toString()
    .replace('\\', '/')
    .toKotlinStringLiteralContent()

private fun String.toKotlinStringLiteralContent(): String {
    val builder = StringBuilder(length + KOTLIN_ESCAPE_BUFFER_PADDING)
    for (char in this) {
        when (char) {
            '$' -> builder.append("\\$")
            '"' -> builder.append("\\\"")
            '\n' -> builder.append("\\n")
            '\r' -> builder.append("\\r")
            '\t' -> builder.append("\\t")
            else -> builder.append(char)
        }
    }
    return builder.toString()
}

internal const val IDE_HELPER_DIRECTORY = ".microsmith/ide"
internal const val IDE_HELPER_SETTINGS_FILE_NAME = "settings.gradle.kts"
internal const val IDE_HELPER_BUILD_FILE_NAME = "build.gradle.kts"
internal const val IDE_HELPER_README_FILE_NAME = "README.md"
private const val KOTLIN_ESCAPE_BUFFER_PADDING = 8
