package me.liam.microsmith.cli.ide

import java.nio.file.Path

internal object IdeHelperProjectTemplates {
    fun renderSettingsGradle(): String = """
        rootProject.name = "microsmith-ide-helper"
    """.trimIndent() + "\n"

    fun renderBuildGradle(classpathEntries: List<Path>): String {
        val dependencyEntries =
            classpathEntries.joinToString(separator = ",\n") { entry ->
                "            \"${entry.toKotlinPathLiteral()}\""
            }

        return buildString {
            appendLine("plugins {")
            appendLine("    id(\"java-library\")")
            appendLine("}")
            appendLine()
            appendLine("dependencies {")
            appendLine("    implementation(")
            appendLine("        files(")
            appendLine(dependencyEntries)
            appendLine("        )")
            appendLine("    )")
            appendLine("}")
        }
    }

    fun renderReadme(): String = """
        # Microsmith JetBrains IDE Helper

        This directory is generated by `microsmith ide refresh`.

        Purpose:
        - provide a minimal Gradle model that exposes Microsmith script-definition/runtime types
        - improve `.microsmith.kts` indexing and type resolution in JetBrains IDEs

        Usage:
        1. run `microsmith ide refresh` from repository root
        2. in your JetBrains IDE, link/import `.microsmith/ide/build.gradle.kts` as a Gradle project
        3. refresh Gradle after upgrading Microsmith CLI or plugin dependencies

        Regeneration:
        - command is idempotent and safe to rerun
        - only files inside `.microsmith/ide` are managed
    """.trimIndent() + "\n"
}
