apply plugin: 'org.jetbrains.kotlin.kapt'
apply plugin: 'tech.mappie.plugin'

dependencies {
    api project(":artifact")
    api project(":artifact-schemas")
    implementation project(":dsl-schemas")
    implementation project(":dsl-schemas-protobuf")
    implementation project(":resolve")
    implementation project(":resolve-schemas-protobuf")
    api libs.spi.tooling.annotations
    kapt libs.spi.tooling.processor
}
