apply plugin: 'org.jetbrains.kotlin.kapt'

dependencies {
    implementation project(":gen")
    implementation project(":gen-services")
    implementation project(":gen-services-dotnet")
    implementation project(":dsl-services-dotnet-packages")
    api libs.spi.tooling.annotations
    kapt libs.spi.tooling.processor
    api libs.coroutines.core
}
