apply plugin: 'org.jetbrains.kotlin.kapt'

dependencies {
    implementation project(":artifact")
    implementation project(":artifact-services-dotnet")
    implementation project(":gen")
    implementation project(":resolve")
    implementation project(":resolve-services-dotnet-packages")
    api libs.spi.tooling.annotations
    kapt libs.spi.tooling.processor
    api libs.coroutines.core
}
