dependencies {
    api project(":dsl")
    api project(":dsl-schemas")
    implementation project(":dsl-schemas-protobuf")
    implementation project(":artifact-schemas")
    implementation project(":artifact-schemas-protobuf")
    implementation project(":lower-schemas-protobuf")
    api project(":gen")
    api libs.coroutines.core
}
