// Generated by Microsmith
using System;

namespace UserService.Api.Generated.Contracts;

public sealed class GetUserPath
{
    public string Id { get; set; } = null!;
}

public sealed class GetUserHeaders
{
    public string? XCorrelationId { get; set; }
}
