// Generated by Microsmith
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace UserService.Api.Generated.Hosting;

public static class MicrosmithHostingExtensions
{
    public static WebApplicationBuilder AddMicrosmith(this WebApplicationBuilder builder)
    {
        builder.Services.AddControllers();
        return builder;
    }

    public static WebApplication MapMicrosmith(this WebApplication app)
    {
        app.MapControllers();
        return app;
    }
}
