dependencies {
    implementation project(":artifact-schemas")
    implementation project(":artifact-schemas-protobuf")
    implementation project(":artifact-schemas-protobuf-rpc")
    implementation project(":gen-schemas-protobuf")
    implementation project(":lower-schemas-protobuf-rpc")
    implementation project(":gen")
    api libs.coroutines.core

    testImplementation project(":dsl")
    testImplementation project(":dsl-schemas")
    testImplementation project(":dsl-schemas-protobuf")
    testImplementation project(":dsl-schemas-protobuf-rpc")
}
