name: Build & Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-and-qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24
          cache: gradle
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Test
        id: test
        run: ./gradlew kotest
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/jvmKotest/*.xml'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: ${{ github.event_name == 'pull_request' }}
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: false
          push-fixes: 'none'
      - uses: github/codeql-action/upload-sarif@v3
        name: Upload SARIF
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json