name: Release & Publish

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: "Which version to bump (patch, minor, major)"
        required: true
        default: Patch
        options:
          - Patch
          - Minor
          - Major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24
          cache: gradle

      - name: Run Axion Release
        id: release
        run: ./gradlew release -Prelease.versionIncrementer=increment${{ github.event.inputs.bump }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.release.outputs.released-version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}